name: build-frontend
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 0 * * *'
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      # cd frontend/
      - name: NPM or Yarn install with caching 📦
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend/
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
        working-directory: frontend/
      - name: Download DB 📙
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "Whazor/k8s-at-home-search"
          latest: true
          fileName: "repos*.db.zz"
          out-file-path: "./frontend/public/"
      - name: Build frontend 🚧
        run: yarn run build
        working-directory: frontend/
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: frontend/
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: frontend/
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: frontend/dist
