name: build-frontend
on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0 * * *"
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: false

      # Step 2: Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules

      # Step 3: Install Dependencies with Yarn
      - name: Install Dependencies 📦
        run: yarn install --frozen-lockfile
        working-directory: web/

      # Step 4: Verify the Existence of download.mjs
      - name: Verify `download.mjs` Exists
        run: |
          if [ ! -f ./scripts/download.mjs ]; then
            echo "Error: download.mjs not found in web/scripts/"
            exit 1
          fi
        working-directory: web/

      # Step 5: Download DB using download.mjs
      - name: Download DB 📙
        run: |
          npx zx ./scripts/download.mjs
        working-directory: web/

      # Step 6: Build the frontend
      - name: Build Web 🚧
        run: yarn run generate
        working-directory: web/

      # Step 7: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: web/

      # Step 8: Run Playwright Tests
      - name: Run Playwright Tests
        run: yarn playwright test
        working-directory: web/

      # Step 9: Upload Playwright Test Reports
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30

      # Step 10: Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: web/dist/static/