name: build-frontend
on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0 * * *"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: false

      # Step 2: Cache node_modules to improve build time
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules

      # Step 3: Install dependencies with Yarn
      - name: Install Dependencies 📦
        run: yarn install --frozen-lockfile
        working-directory: web/

      # Step 4: Download DB
      - name: Download DB 📙
        run: |
          npx zx ./scripts/download.mjs
        working-directory: web/

      # Step 5: Build the frontend
      - name: Build Web 🚧
        run: yarn run generate
        working-directory: web/

      # Step 6: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: web/

      # Step 7: Run Playwright Tests
      - name: Run Playwright Tests
        run: yarn playwright test
        working-directory: web/

      # Step 8: Upload Playwright Test Reports
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30

      # Step 9: Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web/dist/static/