name: build-frontend
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 0 * * *'
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      # cd frontend/
      - name: NPM or Yarn install with caching 📦
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend/
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
        working-directory: frontend/
      - name: Download sqlite.js 📙
        run: |
          mkdir -p frontend/dist/
          wget https://github.com/sql-js/sql.js/releases/download/v1.6.2/sqljs-worker-wasm.zip
          unzip sqljs-worker-wasm.zip -d frontend/public/
      - name: Download DB 📙
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "Whazor/k8s-at-home-search"
          latest: true
          fileName: "repos.db"
          out-file-path: "./frontend/public/"
      - name: Build frontend 🚧
        run: yarn run build
        working-directory: frontend/
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run serve
          working-directory: frontend/
          wait-on: http://localhost:4173/k8s-at-home-search/
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: frontend/dist